.TH "CABRIO" "1" "November 2009" "Steve Maddison" "User Commands"
.SH "NAME"
cabrio \- free open source arcade cabinet emulation front end
.SH "SYNOPSIS"
cabrio
.SH "DESCRIPTION"
Cabrio is a graphical front end for emulators, specifically designed for use in arcade cabinets. It allows you to select games via an intuitive, attractive interface which is easy to use with limited controls, such as a joystick. Cabrio is made available under the GNU General Public License Version 2, meaning anyone can freely download the source code and even contribute to development.
.PP
See http://www.cabrio-fe.org/support/ for help in configuration and usage.
